$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: train_pipeline
description: Retrain deepfake detection model using only a new data samples

inputs:
  model_config:
    type: uri_file
    path: ../model_config.conf
  input_model:
    type: custom_model
    path: azureml:prod_model@latest  
  target_dataset:
    type: uri_folder
    path: azureml:biggan@latest
  source_dataset1:
    type: uri_folder
    path: azureml:gaugan@latest
  source_dataset2:
    type: uri_folder
    path: azureml:cyclegan@latest


outputs:
  best_model:
    type: custom_model
    name: dev_model
    version: 2


settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false


jobs:
  train:
    type: command
    component: ./train_component.yml
    compute: azureml:cpu-cluster
    inputs:
      model_config: ${{parent.inputs.model_config}}
      input_model: ${{parent.inputs.input_model}}
      target_dataset: ${{parent.inputs.target_dataset}}
      source_dataset1: ${{parent.inputs.source_dataset1}}
      source_dataset2: ${{parent.inputs.source_dataset2}}
    outputs:
      output_model: ${{parent.outputs.best_model}}
    